spring:
  application:
    name: expensewise
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: false

server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    com.expensewise: INFO
